//
//  DetailsProtocols.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 25/05/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation

//MARK: Router -
protocol DetailsRouting: class {
    func navigateToTipsModule(viewController: Presentable?, tips: [TipItem], venuePhotoURL: String?)
    func navigateToMapModule(navController: NavigationControlling?)
}

//MARK: Builder -
protocol DetailsBuilding: class {
    func buildModuleWith(venue: Venue, venuePhotoURL: String?) -> FourSquare.Module?
}

//protocol ModuleBuilder: class {
//    func buildModule() -> FourSquare.Module?
//}

//MARK: Presenter -
protocol DetailsPresenting: class {
    func getVenueDetails(venueId: String) 
    func showMap(type: MapType, location: Location)
    func showTipsViewController(tips: [TipItem], venuePhotoURL: String?)
    func dismiss() 
}

//MARK: Interactor -
protocol DetailsInteracting: class {
    var presenter: DetailsPresenting?  { get set }
    func fetchVenueDetails(venueId: String, completion: @escaping (Venue?, FoursquareError?) -> Void)
}

//MARK: View -
protocol DetailsViewable: class {
    var presenter: DetailsPresenting?  { get set }
    func updateWith(viewModel: DetailsViewController.ViewModel)
    func updateWith(error: FoursquareError)
}
