//
//  DetailsViewController.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 25/05/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import UIKit

class DetailsViewController: UIViewController {
    var presenter: DetailsPresenting?
    var headerView: VenueUITableHeaderView?
    let screenWidth = UIScreen.main.bounds.width
    var viewModel: ViewModel?
    
    let transition = Transition()
    var imageFrame = CGRect.zero
    
    @IBOutlet weak var tableView: UITableView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .white
        setUpHeader()
        setUpTableView()
        
        if let viewModel = viewModel {
            presenter?.getVenueDetails(venueId: viewModel.venue.id, venuePhotoURL: viewModel.venuePhotoURL)
        }
    }
    
    func setUpHeader() {
        headerView = VenueUITableHeaderView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: 500), backAction: { [weak self] in
            self?.presenter?.dismiss()
        })
        if let viewModel = viewModel, let category = viewModel.venue.categories.first {
            headerView?.configure(with: VenueUITableHeaderView.ViewModel(title: viewModel.venue.name, description: category.name, imageURL: viewModel.venuePhotoURL))
        }
    }
    
    func setUpTableView() {
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 99
        tableView.contentInset  = UIEdgeInsets(top: 300, left: 0, bottom: 0, right: 0)
        tableView.addSubview(headerView!)
        tableView.tableFooterView = UIView()
    }
    
    func presentMapActionSheet(venue: Venue) {
        let optionMenu = UIAlertController(title: "Directions", message: "Which app do you want to use?", preferredStyle: .actionSheet)
        
        optionMenu.addAction(UIAlertAction(title: "Use Apple Maps", style: .default) { [weak self] _ in
            self?.presenter?.showMap(type: .apple, location: venue.location)
        })
        
        optionMenu.addAction(UIAlertAction(title: "Use Google Maps", style: .default) { [weak self] _ in
            self?.presenter?.showMap(type: .google, location: venue.location)
        })
        
        optionMenu.addAction(UIAlertAction(title: NSLocalizedString("Cancel", comment: "presentmaps.cancel"), style: .cancel))
        
        present(optionMenu, animated: true, completion: nil)
    }
}

// MARK: - StoryboardInstantiatable
extension DetailsViewController: StoryboardInstantiatable {
    static var storyboardName: String {
        return "MapViewController"
    }
    static var instantiateType: StoryboardInstantiateType {
        return .identifier("DetailsViewController")
    }
}

// MARK: - UIScrollViewDelegate
extension DetailsViewController: UIScrollViewDelegate {
    func scrollViewDidEndScrollingAnimation(_ scrollView: UIScrollView) {
        //        self.tableView.reloadData()
    }
    
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
        if headerView != nil {
            let yPos: CGFloat = -scrollView.contentOffset.y
            
            if yPos > 0 {
                var imgRect: CGRect? = headerView?.frame
                imgRect?.origin.y = scrollView.contentOffset.y
                imgRect?.size.height = screenWidth/2 + yPos  - screenWidth/2
                headerView?.frame = imgRect!
                self.tableView.sectionHeaderHeight = (imgRect?.size.height)!
                
            }
        }
    }
}

// MARK: - UITableViewDelegate
extension DetailsViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if indexPath.row == 2 {
            if let venue = viewModel?.venue {
                presentMapActionSheet(venue: venue)
                tableView.deselectRow(at: indexPath, animated: true)
            }
        }
    }
}

// MARK: - UITableViewDataSource
extension DetailsViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        transition.destinationFrame = CGRect(x: 0, y: 0, width: view.frame.width, height: view.frame.height)
        
        if indexPath.row == 0 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "RatingCell") as! RatingUITableViewCell
            if let viewModel = viewModel {
                cell.setup(with: RatingUITableViewCell.ViewModel(rating: viewModel.venue.rating ?? 0.0, visitorsCount: Int(viewModel.venue.stats?.visitsCount ?? 0), likesCount: viewModel.venue.likes?.count ?? 0, checkInsCount: Int(viewModel.venue.stats?.checkinsCount ?? 0), tipCount: viewModel.venue.stats?.tipCount ?? 0))
            }
            return cell
        } else if indexPath.row == 1 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "AddressCell") as! AddressTableViewCell
            if let viewModel = viewModel {
                let categories = viewModel.venue.categories.map{$0.name}
                cell.setup(with: AddressTableViewCell.ViewModel(address: viewModel.venue.location.address ?? "-", categories: categories.joined(separator: ", "), hours: viewModel.venue.hours?.status ?? "-", postalCode: viewModel.venue.location.postalCode ?? "-"))
            }
            return cell
        } else if indexPath.row == 2 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "MapCell") as! MapTableViewCell
            return cell
        } else if indexPath.row == 3 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "PhotoGalleryCell") as! PhotoGalleryTableViewCell
            if let viewModel = viewModel, let groups = viewModel.venue.photos?.groups, let photos = groups[1].items {
                cell.setup(with: PhotoGalleryTableViewCell.ViewModel(photos: photos), imageSelectionHandler: { [weak self] (galleryPreview) in
                    self?.present(galleryPreview, animated: true, completion: nil)
                })
            }
            return cell
        } else if indexPath.row == 4 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "TipsCell") as! TipsTableViewCell
            if let viewModel = viewModel, let groups = viewModel.venue.tips?.groups, let tips = groups.first?.items {
                cell.setup(with: TipsTableViewCell.ViewModel(tips: tips)) { [weak self] in
                    tableView.deselectRow(at: indexPath, animated: true)
                    
                    guard let `self` = self else { return }
                    let a = tableView.convert(cell.frame, to: tableView.superview)
                    self.transition.startingFrame = CGRect(x: a.minX+15, y: a.minY+15, width: 375 / 414 * self.view.frame.width - 30, height: 408 / 736 * self.view.frame.height - 30)
                    
                    self.presenter?.showTipsViewController(tips: tips, venuePhotoURL: viewModel.venuePhotoURL)
                }
            }

            return cell
        } else {
            let cell = tableView.dequeueReusableCell(withIdentifier: "cell")!
            cell.backgroundColor = .white
            return cell
        }
    }
}

extension DetailsViewController {
    struct ViewModel {
        let venue: Venue
        let venuePhotoURL: String?
    }
}

extension DetailsViewController: UIViewControllerTransitioningDelegate {
    func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        transition.transitionMode = .present
        
        return transition
    }
    
    func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        transition.transitionMode = .dismiss
        
        return transition
    }
}

extension DetailsViewController: DetailsViewable {
    func updateWith(error: FoursquareError) {
        if let errorDescription = error.errorDescription, let errorTitle = error.errorUserInfo[NSLocalizedDescriptionKey] as? String {
            InAppNotifications.showNotification(type: InAppNotifications.error, title: errorTitle, message: errorDescription, dismissDelay: 3)
        }
    }
    
    func updateWith(viewModel: DetailsViewController.ViewModel) {
        self.viewModel = viewModel
        tableView.reloadData()
    }
}
