//
//  TipsPresenter.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 10/06/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

class TipsPresenter: TipsPresenting {
    weak private var view: TipsViewable?
    let router: TipsRouting
    
    init(view: TipsViewable, router: TipsRouting) {
        self.view = view
        self.router = router
    }
    
    func buildVenueTableHeaderViewModel(title: String, description: String, imageURL: String?) -> VenueUITableHeaderView.ViewModel {
        return VenueUITableHeaderView.ViewModel(title: title, description: description, imageURL: imageURL)
    }
    
    func buildTipTableCellViewModel(userName: String, userImageURL: String, createdAt: String, tipText: String) -> TipTableViewCell.ViewModel {
        return TipTableViewCell.ViewModel(userName: userName, userImageURL: userImageURL, createdAt: createdAt, tipText: tipText)
    }
    
    func dismiss() {
        if let tipsViewController = view as? TipsViewController {
            router.navigateToDetailsModule(viewController: tipsViewController)
        }
    }
}
