//
//  DetailsPresenter.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 25/05/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

class DetailsPresenter: DetailsPresenting {
    weak private var view: DetailsViewable?
    var interactor: DetailsInteracting?
    let mapURLHandler: MapURLHandling
    let router: DetailsRouting

    init(view: DetailsViewable, interactor: DetailsInteracting?, mapURLHandler: MapURLHandling, router: DetailsRouting) {
        self.view = view
        self.interactor = interactor
        self.mapURLHandler = mapURLHandler
        self.router = router
    }
    
    func showMap(type: MapType, location: Location) {
        mapURLHandler.openMap(location: location, type: type)
    }
    
    func showTipsViewController(tips: [Tip], venuePhotoURL: String?) {
        guard let detailsViewController = view as? DetailsViewController else { return }

        router.navigateToTipsModule(navController: detailsViewController.navigationController, tips: tips, venuePhotoURL: venuePhotoURL)
    }
    
    func dismiss() {
        guard let detailsViewController = view as? DetailsViewController else { return }

        router.navigateToMapModule(navController: detailsViewController.navigationController)
    }
}
