//
//  TipsRouter.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 10/06/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation
import Swinject

class TipsRouter: TipsRouting {
    
    weak var viewController: UIViewController?
    
    init(viewController: UIViewController?) {
        self.viewController = viewController
    }

    func navigateToAnotherModule() {
        if let viewController = self.anotherModuleBuilder()?.buildModule()?.viewController {
            let navController = UINavigationController(rootViewController: viewController)
            self.viewController?.present(navController, animated: true, completion: nil)
        }
    }

    private func anotherModuleBuilder() -> ModuleBuilder? {
        return Container.shared.resolve(ModuleBuilder.self)
    }
}
