//
//  TipsProtocols.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 10/06/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation

//MARK: Router -
protocol TipsRouting: class {
    func navigateToAnotherModule()
}

//MARK: Builder -
protocol TipsBuilding: class {
    func buildModuleWith(tips: [Tip], venuePhotoURL: String?) -> FourSquare.Module?
}

protocol ModuleBuilder: class {
    func buildModule() -> FourSquare.Module?
}

//MARK: Presenter -
protocol TipsPresenting: class {

}

//MARK: Interactor -
protocol TipsInteracting: class {

  var presenter: TipsPresenting?  { get set }
}

//MARK: View -
protocol TipsViewable: class {

  var presenter: TipsPresenting?  { get set }
}
