//
//  TipsBuilder.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 10/06/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Swinject

class TipsBuilder: TipsBuilding {

    private let container: Container
    
    init(container: Container) {
        self.container = container
    }
    
    func buildModuleWith(tips: [Tip], venuePhotoURL: String?) -> FourSquare.Module? {
        registerView(with: tips, venuePhotoURL: venuePhotoURL)
        registerInteractor()
        registerMapURLHandler()
        registerPresenter()
        
        guard let detailsViewController = container.resolve(TipsViewable.self) as? UIViewController else { return nil }
        
        return FourSquare.Module(viewController: detailsViewController)
        
    }
    
    func registerView(with tips: [Tip], venuePhotoURL: String?) {
        container.register(TipsViewable.self, factory: { _ in
            TipsViewController.instantiate()
        }).initCompleted({ (r, view) in
            if let tipsViewController = view as? TipsViewController {
                tipsViewController.presenter = r.resolve(TipsPresenting.self)!
                tipsViewController.update(with: TipsViewController.ViewModel(venuImageURL: venuePhotoURL, tips: tips, title: "", description: ""))
            }
        }).inObjectScope(.container)
    }
    
    func registerMapURLHandler() {
        container.register(MapURLHandling.self, factory: { r in
            MapURLHandler()
        }).inObjectScope(.container)
    }
    func registerPresenter() {
        container.register(TipsPresenting.self, factory: { r in
            TipsPresenter(view: r.resolve(TipsViewable.self)!, interactor: r.resolve(TipsInteracting.self)!)
        }).inObjectScope(.container)
    }
    
    func registerInteractor() {
        container.register(TipsInteracting.self, factory: { r in
            TipsInteractor()
        }).initCompleted ({ (r, interactor) in
            if let tipsInteractor = interactor as? TipsInteractor {
                tipsInteractor.presenter = r.resolve(TipsPresenting.self)
            }
        }).inObjectScope(.container)
    }
}
