//
//  TipsInteractor.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 10/06/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

class TipsInteractor: TipsInteracting {

    weak var presenter: TipsPresenting?
}
