//
//  DetailsRouter.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 25/05/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation
import Swinject

class DetailsRouter: DetailsRouting {
    private weak var tipsModuleBuilder: TipsBuilding?
    weak var navController: NavigationControlling?
    
    init(tipsModuleBuilder: TipsBuilding?) {
        self.tipsModuleBuilder = tipsModuleBuilder
    }

    func navigateToTipsModule(navController: NavigationControlling?, tips: [Tip], venuePhotoURL: String?) {
        self.navController = navController
        if let viewController = tipsModule(tips: tips, venuePhotoURL: venuePhotoURL)?.viewController {
            navController?.pushViewController(viewController, animated: true)
        }
    }
    
    func navigateToMapModule(navController: NavigationControlling?) {
        _ = navController?.popViewController(animated: true)
    }
    
    func tipsModule(tips: [Tip], venuePhotoURL: String?) -> FourSquare.Module? {
        return tipsModuleBuilder?.buildModuleWith(tips: tips, venuePhotoURL: venuePhotoURL)
    }

}
