//
//  DetailsRouter.swift
//  FourSquare
//
//  Created Sameh Mabrouk on 25/05/2019.
//  Copyright © 2019 VanMoof. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation
import Swinject

class DetailsRouter: DetailsRouting {
    private weak var tipsModuleBuilder: TipsBuilding?
    weak var viewController: Presentable?
    
    init(tipsModuleBuilder: TipsBuilding?) {
        self.tipsModuleBuilder = tipsModuleBuilder
    }

    func navigateToTipsModule(viewController: Presentable?, tips: [TipItem], venuePhotoURL: String?) {
        self.viewController = viewController
        if let tipsViewController = tipsModule(tips: tips, venuePhotoURL: venuePhotoURL)?.viewController, let detailsViewController = viewController as? DetailsViewController {
            
            tipsViewController.transitioningDelegate = detailsViewController
            tipsViewController.modalPresentationStyle = .custom
            detailsViewController.present(tipsViewController, animated: true, completion: nil)
        }
    }
    
    func navigateToMapModule(navController: NavigationControlling?) {
        _ = navController?.popViewController(animated: true)
    }
    
    func tipsModule(tips: [TipItem], venuePhotoURL: String?) -> FourSquare.Module? {
        return tipsModuleBuilder?.buildModuleWith(tips: tips, venuePhotoURL: venuePhotoURL)
    }

}
