# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FourSquare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourSquare
  pod 'Swinject', '~> 2.1'
  pod 'Alamofire', '~> 4.8.0'
  pod 'Nuke', '7.6'

  target 'FourSquareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FourSquareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
